### ISSUE TITLE
Close gracefully

### ISSUE THREAD

**Issue by gmaclennan** [digidem/osm-p2p-db#28]
We need a method to close all the open stores gracefully, both level and chunk stores. There are many of them.

I'm unclear right now whether when electron quits it waits for any pending leveldb writes, we should make sure and close osm-p2p-db in the quit handler.

We need this function for cleanup of test dbs when running in the browser.

**Comment by gmaclennan** [comment]
See https://github.com/digidem/osm-p2p/issues/2
and https://github.com/digidem/osm-p2p-db/issues/51

**Comment by noffle** [comment]
FWIW, I still think that a `close()` convenience method on `osm-p2p-*db*` would be useful and reasonable to add.
