### ISSUE TITLE
ready() method does not wait for changeset index to catch up

### ISSUE THREAD

**Issue by gmaclennan** [digidem/osm-p2p-db#30]
[`osm.ready()`](https://github.com/digidem/osm-p2p-db/blob/master/index.js#L103) does not wait for the changeset index. As well as fixing this we should make this more robust so that we don't hit this bug again when we add additional indexes, perhaps store all indexes on `this._indexes` and iterate over each one in `ready()`?

**Comment by noffle** [comment]
I think having a list of indexes just pushes the problem to remembering to add the index to the index list. What would be nice is maybe if our tests did a slowdb round, where we'd be more likely to catch issues related to indexes not being caught up.
