### ISSUE TITLE
opts.size === chunkLength?

### ISSUE THREAD

**Issue by gmaclennan** [digidem/osm-p2p-db#7]
Should the `opts.size` argument be equal to [`chunkLength`](https://www.npmjs.com/package/abstract-chunk-store#chunkstore--new-chunkstorechunklength) which is passed when creating the chunk-store? Maybe rename to `opts.chunkLength`? Can we read this from the chunkStore rather than requiring it? What would happen if it was different?

**Comment by substack** [comment]
Yes, this can be confusing, but the opts.size must be the exact same as passed to the chunk store. It would be good if chunk store modules exposed a `size` property I think.

**Comment by substack** [comment]
With the upstream fixes in abstract-chunk-store, the size is now implicitly taken from the store's chunkLength property in 3.0.0.
