### ISSUE TITLE
Modifying a fork without merging conflict

### ISSUE THREAD

**Issue by gmaclennan** [digidem/osm-p2p-db#8]
From the [readme](https://github.com/digidem/osm-p2p-db#replication) 'To merge these "conflicts" back into a single value, use `osm.put(id, doc, cb)` to store the desired document value.'

How do you update a doc that has a fork without merging? I can think of several scenarios where a user would need to update a forked doc (i.e. update one of the forks) and postpone dealing with merging / resolving conflicts.

**Comment by substack** [comment]
You can give `put()` an array of `opts.links` to point back at. If `opts.links` isn't defined, the default value is the most recent set of updates.
